import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, CircleAlert, Facebook, Image as ImageIcon, Loader2, Send, Video } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

type Format = "Feed" | "Stories" | "Reel";

function dateKey(year: number, month: number, day: number) { return `${year}-${String(month + 1).padStart(2, "0")}-${String(day).padStart(2, "0")}`; }
function statusClass(status: string) {
  if (status === "Publicado") return "bg-[#e5efe8] text-[#203d37] hover:bg-[#e5efe8]";
  if (status === "Listo para publicar") return "bg-[#fff0d5] text-[#735925] hover:bg-[#fff0d5]";
  if (status === "Error") return "bg-red-50 text-red-700 hover:bg-red-50";
  return "bg-stone-100 text-stone-600 hover:bg-stone-100";
}

export default function CalendarVisual() {
  const utils = trpc.useUtils();
  const { data, isLoading } = trpc.media.dashboard.useQuery(undefined, { retry: false });
  const facebook = trpc.media.facebookStatus.useQuery(undefined, { retry: false });
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [selectedDate, setSelectedDate] = useState("");
  const [selectedAsset, setSelectedAsset] = useState<number | null>(null);
  const [format, setFormat] = useState<Format>("Feed");
  const [note, setNote] = useState("");
  const assign = trpc.media.assignToCalendar.useMutation({ onSuccess: () => { utils.media.dashboard.invalidate(); setNote(""); toast.success("Borrador agregado a la cola editorial"); }, onError: error => toast.error(error.message) });
  const ready = trpc.media.readyForFacebook.useMutation({ onSuccess: () => { utils.media.dashboard.invalidate(); toast.success("Borrador revisado y listo para tu confirmación de publicación"); }, onError: error => toast.error(error.message) });
  const publish = trpc.media.publishToFacebook.useMutation({ onSuccess: () => { utils.media.dashboard.invalidate(); toast.success("Contenido publicado en Facebook"); }, onError: error => toast.error(error.message) });
  useEffect(() => {
    const state = new URLSearchParams(window.location.search).get("facebook");
    if (state === "connected") { toast.success("Página de Facebook conectada"); facebook.refetch(); window.history.replaceState({}, "", "/calendario"); }
    if (state === "error") { toast.error(new URLSearchParams(window.location.search).get("reason") || "No se pudo conectar Facebook"); window.history.replaceState({}, "", "/calendario"); }
  }, []);

  const assets = data?.assets ?? [];
  const slots = data?.slots ?? [];
  const contentAssets = assets.filter(asset => asset.backupVerified && (asset.category === "Trabajos de Geo Carpentry" || asset.category === "Videos"));
  const year = month.getFullYear(); const monthIndex = month.getMonth();
  const monthTitle = month.toLocaleDateString("es-MX", { month: "long", year: "numeric" });
  const firstWeekday = (new Date(year, monthIndex, 1).getDay() + 6) % 7;
  const dayCount = new Date(year, monthIndex + 1, 0).getDate();
  const cells = useMemo(() => Array.from({ length: firstWeekday + dayCount }, (_, index) => index < firstWeekday ? null : index - firstWeekday + 1), [firstWeekday, dayCount]);
  const readyCount = slots.filter(slot => slot.status === "Listo para publicar").length;

  if (isLoading) return <div className="grid min-h-[75vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-[#203d37]" /></div>;
  return <div className="mx-auto max-w-7xl space-y-7"><header className="flex flex-col justify-between gap-5 border-b border-stone-300 pb-6 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#9c6b20]">Planificación editorial</p><h1 className="mt-2 font-serif text-4xl tracking-tight text-[#203d37] md:text-5xl">Calendario visual de contenido.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-stone-600">Prepara cada pieza, revísala y confirma la publicación manualmente. La app nunca publica por calendario ni sin una acción final tuya.</p></div><div className="flex flex-wrap gap-2"><Badge className="h-fit bg-[#e5efe8] px-4 py-2 text-[#203d37] hover:bg-[#e5efe8]"><CalendarDays className="mr-2 h-4 w-4" />{slots.length} borrador(es)</Badge>{readyCount > 0 && <Badge className="h-fit bg-[#fff0d5] px-4 py-2 text-[#735925] hover:bg-[#fff0d5]"><Send className="mr-2 h-4 w-4" />{readyCount} listo(s)</Badge>}</div></header>
    <FacebookConnectionCard configured={Boolean(facebook.data?.configured)} connected={Boolean(facebook.data?.connected)} pageName={facebook.data?.pageName ?? null} />
    <div className="grid gap-6 xl:grid-cols-[1fr_360px]"><Card className="border-stone-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between border-b border-stone-100"><CardTitle className="font-serif text-2xl text-[#203d37]">{monthTitle}</CardTitle><div className="flex gap-2"><Button variant="outline" size="icon" aria-label="Mes anterior" onClick={() => setMonth(new Date(year, monthIndex - 1, 1))}><ChevronLeft className="h-4 w-4" /></Button><Button variant="outline" size="icon" aria-label="Mes siguiente" onClick={() => setMonth(new Date(year, monthIndex + 1, 1))}><ChevronRight className="h-4 w-4" /></Button></div></CardHeader><CardContent className="p-3 md:p-5"><div className="grid grid-cols-7 border-l border-t border-stone-200 text-center text-[10px] font-bold uppercase tracking-[0.12em] text-stone-500">{["Lun", "Mar", "Mié", "Jue", "Vie", "Sáb", "Dom"].map(day => <div className="border-b border-r border-stone-200 bg-stone-50 py-3" key={day}>{day}</div>)}{cells.map((day, index) => { if (!day) return <div className="min-h-28 border-b border-r border-stone-200 bg-stone-50/40" key={`blank-${index}`} />; const key = dateKey(year, monthIndex, day); const daySlots = slots.filter(slot => slot.scheduledDate === key); return <button type="button" onClick={() => setSelectedDate(key)} className={`min-h-28 border-b border-r border-stone-200 p-2 text-left transition hover:bg-[#fffaf0] ${selectedDate === key ? "bg-[#fff4d8] ring-2 ring-inset ring-[#e7bd68]" : "bg-white"}`} key={key}><span className="grid h-6 w-6 place-items-center rounded-full text-xs font-semibold text-[#203d37]">{day}</span><div className="mt-2 space-y-1">{daySlots.slice(0, 2).map(slot => { const asset = assets.find(item => item.id === slot.assetId); return <div key={slot.id} className={`truncate rounded px-1.5 py-1 text-[10px] font-medium ${slot.status === "Publicado" ? "bg-[#315a51] text-white" : "bg-[#203d37] text-white"}`}>{slot.format === "Reel" ? "Reel · " : ""}{asset?.originalFilename ?? "Archivo"}</div>; })}{daySlots.length > 2 && <p className="text-[10px] text-stone-500">+{daySlots.length - 2} más</p>}</div></button>; })}</div></CardContent></Card>
      <Card className="h-fit border-[#e7d7b6] bg-[#fffaf0] shadow-sm"><CardHeader><CardTitle className="font-serif text-2xl text-[#5d4318]">Asignar borrador</CardTitle></CardHeader><CardContent className="space-y-4"><div><Label>Fecha elegida</Label><div className="mt-1 rounded-lg border border-[#e7d7b6] bg-white px-3 py-2 text-sm text-[#5d4318]">{selectedDate || "Selecciona un día en el calendario"}</div></div><div><Label>Archivo de obra</Label><Select value={selectedAsset ? String(selectedAsset) : undefined} onValueChange={value => setSelectedAsset(Number(value))}><SelectTrigger className="mt-1 bg-white"><SelectValue placeholder="Elige un archivo" /></SelectTrigger><SelectContent>{contentAssets.map(asset => <SelectItem key={asset.id} value={String(asset.id)}>{asset.originalFilename}</SelectItem>)}</SelectContent></Select></div>{selectedAsset ? <SelectedAssetPreview asset={assets.find(asset => asset.id === selectedAsset)} /> : null}<div><Label>Formato</Label><Select value={format} onValueChange={value => setFormat(value as Format)}><SelectTrigger className="mt-1 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Feed">Feed · imagen</SelectItem><SelectItem value="Reel">Reel · video vertical</SelectItem><SelectItem value="Stories">Stories · borrador</SelectItem></SelectContent></Select></div><div><Label>Copy para Facebook</Label><Textarea className="mt-1 bg-white" value={note} onChange={event => setNote(event.target.value)} placeholder="Texto, CTA y hashtags" /></div><Button className="w-full bg-[#203d37] hover:bg-[#16312b]" disabled={!selectedDate || !selectedAsset || assign.isPending} onClick={() => selectedAsset && selectedDate && assign.mutate({ assetId: selectedAsset, scheduledDate: selectedDate, format, captionNote: note || undefined })}>{assign.isPending ? "Asignando…" : "Agregar a la cola"}</Button><p className="text-xs leading-5 text-[#735925]">Los Reels deben ser MP4 verticales de 3–90 segundos; la preparación valida el tipo de archivo antes de habilitar publicación.</p></CardContent></Card></div>
    <EditorialQueue slots={slots} assets={assets} facebookConnected={Boolean(facebook.data?.connected)} configured={Boolean(facebook.data?.configured)} preparing={ready.isPending} publishing={publish.isPending} onPrepare={slotId => ready.mutate({ slotId })} onPublish={slotId => { if (window.confirm("¿Confirmas que deseas publicar esta pieza ahora en la Página de Facebook conectada? Esta acción será pública.")) publish.mutate({ slotId }); }} />
  </div>;
}

function FacebookConnectionCard({ configured, connected, pageName }: { configured: boolean; connected: boolean; pageName: string | null }) {
  if (connected) return <Card className="border-[#c9ddd1] bg-[#f5faf6]"><CardContent className="flex flex-col justify-between gap-4 p-5 md:flex-row md:items-center"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#203d37] text-white"><Facebook className="h-5 w-5" /></div><div><p className="font-semibold text-[#203d37]">Página conectada: {pageName}</p><p className="mt-1 text-sm text-stone-600">Puedes preparar Feed y Reels. Cada publicación seguirá exigiendo tu confirmación explícita.</p></div></div><Badge className="bg-[#e5efe8] text-[#203d37] hover:bg-[#e5efe8]"><CheckCircle2 className="mr-1 h-3.5 w-3.5" />Autorizada</Badge></CardContent></Card>;
  return <Card className="border-[#e7d7b6] bg-[#fffaf0]"><CardContent className="flex flex-col justify-between gap-4 p-5 md:flex-row md:items-center"><div className="flex items-start gap-3"><CircleAlert className="mt-0.5 h-5 w-5 text-[#9c6b20]" /><div><p className="font-semibold text-[#5d4318]">{configured ? "Conecta la Página de Facebook" : "La configuración de Facebook aún no está disponible"}</p><p className="mt-1 text-sm leading-5 text-[#735925]">{configured ? "Autoriza la Página de Geo Carpentry en Meta. La conexión guarda el token cifrado solo en el servidor." : "Completa la configuración de Meta para habilitar la conexión."}</p></div></div>{configured && <Button className="bg-[#203d37] hover:bg-[#16312b]" onClick={() => window.location.assign("/api/facebook/connect")}><Facebook className="mr-2 h-4 w-4" />Conectar Facebook</Button>}</CardContent></Card>;
}

function EditorialQueue({ slots, assets, facebookConnected, configured, preparing, publishing, onPrepare, onPublish }: { slots: any[]; assets: any[]; facebookConnected: boolean; configured: boolean; preparing: boolean; publishing: boolean; onPrepare: (slotId: number) => void; onPublish: (slotId: number) => void }) {
  return <Card className="border-stone-200"><CardHeader><CardTitle className="flex items-center gap-2 font-serif text-2xl text-[#203d37]"><Send className="h-5 w-5 text-[#b77a21]" />Cola editorial de Facebook</CardTitle></CardHeader><CardContent>{slots.length ? <div className="space-y-3">{slots.map(slot => { const asset = assets.find(item => item.id === slot.assetId); const canPrepare = ["Borrador", "Aprobado", "Error"].includes(slot.status) && slot.format !== "Stories"; return <div key={slot.id} className="flex flex-col gap-4 rounded-xl border border-stone-200 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-medium text-[#203d37]">{asset?.originalFilename ?? "Archivo"}</p><Badge className={statusClass(slot.status)}>{slot.status}</Badge><Badge variant="outline">{slot.format}</Badge></div><p className="mt-1 text-sm text-stone-600">{slot.scheduledDate}{slot.captionNote ? ` · ${slot.captionNote}` : " · Sin copy aún"}</p>{slot.publishError && <p className="mt-1 text-xs text-red-700">Último error: {slot.publishError}</p>}{slot.facebookPostId && <p className="mt-1 text-xs text-[#315a51]">Facebook ID: {slot.facebookPostId}</p>}</div><div className="flex shrink-0 gap-2">{canPrepare && <Button variant="outline" onClick={() => onPrepare(slot.id)} disabled={preparing}>{preparing ? <Loader2 className="h-4 w-4 animate-spin" /> : "Preparar"}</Button>}{slot.status === "Listo para publicar" && <Button className="bg-[#203d37] hover:bg-[#16312b]" disabled={!facebookConnected || publishing} onClick={() => onPublish(slot.id)}>{publishing ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{facebookConnected ? "Publicar ahora" : configured ? "Conecta Facebook" : "Configura Facebook"}</Button>}</div></div>; })}</div> : <div className="rounded-xl bg-stone-50 p-10 text-center text-sm text-stone-500">Agrega un archivo al calendario para iniciar una publicación o un Reel revisable.</div>}</CardContent></Card>;
}

function SelectedAssetPreview({ asset }: { asset: any }) { if (!asset) return null; const canShowImage = asset.mediaType === "image" && !asset.mimeType.includes("heic"); return <div className="overflow-hidden rounded-xl border border-[#e7d7b6] bg-white"><div className="h-32 bg-stone-100">{canShowImage ? <img className="h-full w-full object-cover" src={asset.storageUrl} alt={asset.originalFilename} /> : <div className="grid h-full place-items-center text-stone-400"><Video className="h-6 w-6" /></div>}</div><p className="truncate px-3 py-2 text-xs font-medium text-[#5d4318]">{asset.originalFilename}</p></div>; }
